create table if not exists monthly_ebe (
  id bigint generated by default as identity primary key,
  month date not null unique, -- First day of the month, e.g., '2023-01-01'
  turnover numeric not null default 0,
  purchases numeric not null default 0,
  external_charges numeric not null default 0,
  salaries numeric not null default 0,
  production_taxes numeric not null default 0,
  ebe numeric generated always as (turnover - (purchases + external_charges + salaries + production_taxes)) stored,
  margin_percent numeric generated always as (
    case 
      when turnover = 0 then 0 
      else ((turnover - (purchases + external_charges + salaries + production_taxes)) / turnover) * 100 
    end
  ) stored,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Or if 'generated always' is not supported by the specific postgres version or preference for app-side calc (safer for simple app logic often):
-- We will calculate EBE and margin_percent in the application and store them, or just store the inputs and calculate on read. 
-- Let's store inputs and calculate on read/write to be safe and simple with Supabase client.

create table if not exists monthly_ebe (
  id bigint generated by default as identity primary key,
  month date not null unique,
  turnover numeric not null default 0,
  purchases numeric not null default 0,
  external_charges numeric not null default 0,
  salaries numeric not null default 0,
  production_taxes numeric not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
